#docker-compose.yml
version: '2'
services:
    web:
        build: ./web
        container_name: silex-static
        command: node_modules/.bin/nodemon --exec npm start
        environment:
            PORT: 4000
        ports:
            - "4000:4000"
        volumes:
            - ./web:/home/web